server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      force: true
      enabled: true
      charset: UTF-8
spring:
  redis:
    host: 192.168.178.114
    port: 6379
    password: 110614
    database: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: health_backend
  dubbo:
    port: 20880
    registry: zookeeper://192.168.178.114:2181

