server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      force: true
      enabled: true
      charset: UTF-8
hepagehelper:
  lperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.14.181.108:3306/health?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 110614
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.178.114
    port: 6379
    password: 110614
    database: 0
  application:
    name: health_service_provider
  dubbo:
    port: 20880
    server: true
    registry: zookeeper://192.168.178.114:2181
  main:
    allowCircularReferences: true
mybatis:
  type-aliases-package: com.home.model
  mapper-locations: classpath:com/home/dao/*.xml
